#!/usr/bin/env ruby

APP_ROOT = File.expand_path('..', __dir__)
$LOAD_PATH.unshift(File.join(APP_ROOT, 'lib'))

require 'test_process_automator'

class Frontend
  attr_accessor :log_file_prefix

  def start_command
    "echo 'This would be the Frontend start command'"
  end

  def sleep_after_start
    1
  end

  def kill_command
    "echo 'This would be the Frontend kill command'"
  end

  def sleep_after_kill
    1
  end
end

class Backend
  attr_accessor :log_file_prefix

  def start_command
    "echo 'This would be the Backend start command'"
  end

  def sleep_after_start
    1
  end

  def kill_command
    "echo 'This would be the Backend kill command'"
  end

  def sleep_after_kill
    1
  end
end

runner = TestProcessAutomator.tpa_runner('front_and_back')
runner.add_process(frontend: Frontend.new,
                   backend:  Backend.new)

runner.start!(:frontend)
puts 'Frontend only Tests would run here ...'
runner.kill!(:frontend)

puts "\n .... and .... \n\n"

runner.start!(:frontend, :backend)
puts 'combined Frontend and Backend Tests would run here ...'
runner.kill!(:frontend, :backend)
