#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'runnerbean'
require_relative 'processes/frontend'
require_relative 'processes/backend'

runner = Runnerbean.runner('front_and_back')
runner.add_process(frontend: Frontend.new,
                   backend:  Backend.new)

runner.start!(:frontend)
puts 'Frontend only Tests would run here ...'
runner.kill!(:frontend)

puts "\n .... and .... \n\n"

runner.start!(:frontend, :backend)
puts 'combined Frontend and Backend Tests would run here ...'
runner.kill!(:frontend, :backend)
