#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'runnerbean'
require_relative 'processes/my_test_process'

runner = Runnerbean.runner('simple')
runner.add_process(my_process: MyTestProcess.new)

runner.start!(:my_process)
puts 'Tests would run here ...'
runner.kill!(:my_process)
